export const STORAGE_CACHE_KEY = 'CHANNEX_BL_CACHE';
export const SESSION_ADD = 'SESSION_ADD';
export const CHOOSE_PROPERTY = 'CHOOSE_PROPERTY';
export const CHOOSE_GROUP = 'CHOOSE_GROUP';

export const PROPERTIES_LOAD = 'PROPERTIES_LOAD';
export const PROPERTIES_ADD = 'PROPERTIES_ADD';
export const PROPERTIES_DROP = 'PROPERTIES_DROP';

export const PROPERTIES_HEALTH_LOAD = 'PROPERTIES_HEALTH_LOAD';

export const ROOM_TYPES_LOAD = 'ROOM_TYPES_LOAD';
export const ROOM_TYPES_ADD = 'ROOM_TYPES_ADD';
export const ROOM_TYPES_DROP = 'ROOM_TYPES_DROP';

export const RATE_CATEGORIES_LOAD = 'RATE_CATEGORIES_LOAD';
export const RATE_CATEGORIES_ADD = 'RATE_CATEGORIES_ADD';
export const RATE_CATEGORIES_DROP = 'RATE_CATEGORIES_DROP';

export const RATE_PLANS_LOAD = 'RATE_PLANS_LOAD';
export const RATE_PLANS_ADD = 'RATE_PLANS_ADD';
export const RATE_PLANS_DROP = 'RATE_PLANS_DROP';

export const CHANNELS_LOAD = 'CHANNELS_LOAD';
export const CHANNELS_ADD = 'CHANNELS_ADD';
export const CHANNELS_DROP = 'CHANNELS_DROP';
export const CHANNELS_HEALTH_LOAD = 'CHANNELS_HEALTH_LOAD';

export const USER_ADD = 'USER_ADD';
export const USERS_LOAD = 'USERS_LOAD';
export const USERS_ADD = 'USERS_ADD';
export const USERS_DROP = 'USERS_DROP';

export const WHITE_LABEL_PARTNERS_LOAD = 'WHITE_LABEL_PARTNERS_LOAD';
export const WHITE_LABEL_PARTNERS_ADD = 'WHITE_LABEL_PARTNERS_ADD';
export const WHITE_LABEL_PARTNERS_DROP = 'WHITE_LABEL_PARTNERS_DROP';

export const WHITE_LABEL_DOMAINS_LOAD = 'WHITE_LABEL_DOMAINS_LOAD';
export const WHITE_LABEL_DOMAINS_ADD = 'WHITE_LABEL_DOMAINS_ADD';
export const WHITE_LABEL_DOMAINS_DROP = 'WHITE_LABEL_DOMAINS_DROP';

export const WHITE_LABEL_EMAIL_SETTINGS_LOAD = 'WHITE_LABEL_EMAIL_SETTINGS_LOAD';
export const WHITE_LABEL_EMAIL_SETTINGS_ADD = 'WHITE_LABEL_EMAIL_SETTINGS_ADD';
export const WHITE_LABEL_EMAIL_SETTINGS_DROP = 'WHITE_LABEL_EMAIL_SETTINGS_DROP';

export const EMAIL_TEMPLATES_LOAD = 'EMAIL_TEMPLATES_LOAD';
export const EMAIL_TEMPLATES_ADD = 'EMAIL_TEMPLATES_ADD';
export const EMAIL_TEMPLATES_DROP = 'EMAIL_TEMPLATES_DROP';

export const TASKS_LOAD = 'TASKS_LOAD';

export const TAXES_LOAD = 'TAXES_LOAD';
export const TAXES_ADD = 'TAXES_ADD';
export const TAXES_DROP = 'TAXES_DROP';

export const TAX_SETS_LOAD = 'TAX_SETS_LOAD';
export const TAX_SETS_ADD = 'TAX_SETS_ADD';
export const TAX_SETS_DROP = 'TAX_SETS_DROP';

export const GROUPS_LOAD = 'GROUPS_LOAD';
export const GROUPS_ADD = 'GROUPS_ADD';
export const GROUPS_DROP = 'GROUPS_DROP';

export const CHANNEL_EVENTS_LOAD = 'CHANNEL_EVENTS_LOAD';
export const BOOKINGS_LOAD = 'BOOKINGS_LOAD';
export const BOOKINGS_ADD = 'BOOKINGS_ADD';

export const HOTEL_POLICIES_LOAD = 'HOTEL_POLICIES_LOAD';
export const HOTEL_POLICIES_ADD = 'HOTEL_POLICIES_ADD';
export const HOTEL_POLICIES_DROP = 'HOTEL_POLICIES_DROP';

export const CANCELLATION_POLICIES_LOAD = 'CANCELLATION_POLICIES_LOAD';
export const CANCELLATION_POLICIES_ADD = 'CANCELLATION_POLICIES_ADD';
export const CANCELLATION_POLICIES_DROP = 'CANCELLATION_POLICIES_DROP';
