export const STORAGE_CACHE_KEY = 'CHANNEX_BL_CACHE';
export const SESSION_ADD = 'SESSION_ADD';

export const HOTELS_LOAD = 'HOTELS_LOAD';
export const HOTELS_ADD = 'HOTELS_ADD';
export const HOTELS_DROP = 'HOTELS_DROP';

export const ROOM_TYPES_LOAD = 'ROOM_TYPES_LOAD';
export const ROOM_TYPES_ADD = 'ROOM_TYPES_ADD';
export const ROOM_TYPES_DROP = 'ROOM_TYPES_DROP';

export const RATE_PLANS_LOAD = 'RATE_PLANS_LOAD';
export const RATE_PLANS_ADD = 'RATE_PLANS_ADD';
export const RATE_PLANS_DROP = 'RATE_PLANS_DROP';

export const CHANNELS_LOAD = 'CHANNELS_LOAD';
export const CHANNELs_ADD = 'CHANNELS_ADD';
export const CHANNELS_DROP = 'CHANNELS_DROP';

export const USERS_LOAD = 'USERS_LOAD';
export const USERS_ADD = 'USERS_ADD';
export const USERS_DROP = 'USERS_DROP';

export const WHITE_LABEL_PARTNERS_LOAD = 'WHITE_LABEL_PARTNERS_LOAD';
export const WHITE_LABEL_PARTNERS_ADD = 'WHITE_LABEL_PARTNERS_ADD';
export const WHITE_LABEL_PARTNERS_DROP = 'WHITE_LABEL_PARTNERS_DROP';

export const WHITE_LABEL_DOMAINS_LOAD = 'WHITE_LABEL_DOMAINS_LOAD';
export const WHITE_LABEL_DOMAINS_ADD = 'WHITE_LABEL_DOMAINS_ADD';
export const WHITE_LABEL_DOMAINS_DROP = 'WHITE_LABEL_DOMAINS_DROP';

export const WHITE_LABEL_EMAIL_SETTINGS_LOAD = 'WHITE_LABEL_EMAIL_SETTINGS_LOAD';
export const WHITE_LABEL_EMAIL_SETTINGS_ADD = 'WHITE_LABEL_EMAIL_SETTINGS_ADD';
export const WHITE_LABEL_EMAIL_SETTINGS_DROP = 'WHITE_LABEL_EMAIL_SETTINGS_DROP';

export const EMAIL_TEMPLATES_LOAD = 'EMAIL_TEMPLATES_LOAD';
export const EMAIL_TEMPLATES_ADD = 'EMAIL_TEMPLATES_ADD';
export const EMAIL_TEMPLATES_DROP = 'EMAIL_TEMPLATES_DROP';
